### ISSUE TITLE
What is different in this one than the original "hack_interview" ?

### ISSUE THREAD

**Issue by 721-atikshaikh** [ivnvxd/hack-interview#1]
Can you please mention in the readme whats different than the original project ?

**Comment by ivnvxd** [comment]
Why? And what exactly should I write in the differences? That other libraries are used, there is a possibility to choose a model for generating answers, the UI is different. Event handling is also different in general. And about all the other differences too?
It seems to me that this is unnecessary information for the user of the application for the readme file.
